const assert=require('node:assert/strict');
const path=require('node:path');
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'});
 const page=await browser.newPage({viewport:{width:1600,height:1050}});
 const errors=[];page.on('pageerror',error=>errors.push(error.message));
 await page.setContent('<html><body></body></html>');
 await page.addScriptTag({path:path.join(__dirname,'.build/fixture.js')});
 const pool=page.locator('sg-table sg-area.discard-area');
 await pool.locator('sg-card').first().waitFor();
 assert.equal(await pool.locator('sg-card').count(),100);
 const pile=page.locator('sg-table sg-paiarea');
 assert.equal(await pile.locator('sg-card').count(),100);
 assert.equal(await pile.locator('sg-card .card-front').first().isVisible(),false);
 assert.equal(await pile.locator('sg-card .card-back').first().isVisible(),true);
 await page.evaluate(()=>window.fixture.controller.showCard(window.fixture.table.paiArea.cardArea.firstElementChild.cardRef));
 await pile.locator('sg-card .card-front').first().waitFor({state:'visible'});
 assert.equal(await pile.locator('sg-card .card-back').first().isVisible(),false);
 await page.evaluate(()=>window.fixture.controller.resetCard(window.fixture.table.paiArea.cardArea.firstElementChild.cardRef));
 await pile.locator('sg-card .card-back').first().waitFor({state:'visible'});
 const first=pool.locator('sg-card').nth(0),third=pool.locator('sg-card').nth(2);
 const a=await third.boundingBox(),b=await first.boundingBox();
 await page.mouse.move(a.x+15,a.y+20);await page.mouse.down();
 await page.mouse.move(b.x+2,b.y+20,{steps:8});
 await page.waitForTimeout(100);
 assert.equal(await pool.evaluate(node=>node.classList.contains('drag-target')),true);
 await page.mouse.up();
 await page.waitForFunction(()=>window.fixture.read('game/6/tableDecks/discard/cards/c2').order===0);
 const opponent=page.locator('sg-player[data-key="p2"]');
 const target=await opponent.boundingBox();
 async function dragToPlayer(){const r=await first.boundingBox();await page.mouse.move(r.x+15,r.y+20);await page.mouse.down();await page.mouse.move(target.x+210,target.y+70,{steps:12});await page.waitForTimeout(80);assert.equal(await opponent.evaluate(n=>n.classList.contains('drag-target')),true);await page.mouse.up();await opponent.locator('.drop-picker').waitFor({state:'visible'});}
 await page.waitForTimeout(200);await dragToPlayer();
 await opponent.locator('.drop-cancel').click();
 await page.waitForTimeout(260);
 assert.equal(await page.evaluate(()=>Object.keys(window.fixture.read('game/6/p2/hand/cards')).length),5);
 await dragToPlayer();await opponent.locator('[data-area="handArea"]').click();
 await page.waitForFunction(()=>Object.keys(window.fixture.read('game/6/p2/hand/cards')).length===6);
 assert.equal(await page.evaluate(()=>window.fixture.read('game/6/tableDecks/discard/cards/c0')),null);
 await page.evaluate(()=>{const f=window.fixture,p=f.table.playerDoms.find(p=>p.dataset.key==='p2');p.openDropPicker('game/6/tableDecks/pai/cards/c0',['game/6/tableDecks/pai/cards/c0']);});
 assert.equal(await opponent.locator('[data-effect="闪电"]').isVisible(),true);
 assert.equal(await page.evaluate(()=>window.fixture.read('game/6/tableDecks/pai/cards/c0')!==null),true);
 await opponent.locator('[data-effect="闪电"]').click();
 await page.waitForFunction(()=>Object.values(window.fixture.read('game/6/p2/pan/cards')||{}).some(c=>c.judgmentEffect==='闪电'));
 assert.equal(await opponent.locator('sg-card.pan-area-card').first().getAttribute('data-effect'),'电');
 await page.evaluate(()=>{const p=window.fixture.table.playerDoms.find(p=>p.dataset.key==='p2');p.openDropPicker('game/6/tableDecks/pai/cards/c1',['game/6/tableDecks/pai/cards/c1']);});
 assert.equal(await opponent.locator('[data-area="handArea"]').isVisible(),true);
 assert.equal(await opponent.locator('[data-effect="闪电"]').isDisabled(),true);
 await opponent.locator('[data-effect="乐不思蜀"]').click();
 await page.waitForFunction(()=>Object.keys(window.fixture.read('game/6/p2/pan/cards')||{}).length===2);
 assert.deepEqual(await page.evaluate(()=>Object.values(window.fixture.read('game/6/p2/pan/cards')).sort((a,b)=>a.order-b.order).map(c=>c.judgmentEffect)),['闪电','乐不思蜀']);
  await page.evaluate(async()=>{
    const f=window.fixture,p=f.table.playerDoms.find(p=>p.dataset.key==='p2');
    await f.controller.setScalarValue(p.hpWc.hpRef,'10/14');
    await f.controller.togglePlayerStatus(p.playerRef,0);
    await f.controller.togglePlayerStatus(p.playerRef,1);
  });
  await page.waitForFunction(()=>window.fixture.read('game/6/p2/hp')==='10/14'&&window.fixture.read('game/6/p2/debuff')==='11');
  const batch=await page.evaluate(async()=>{
   const f=window.fixture,c=f.controller;
   [...c.selectedCards].forEach(card=>card.unselectCard());
   const cards=[...f.table.paiArea.cardArea.children].slice(0,2);
   const ids=cards.map(card=>card.cardData.id);
   cards.forEach(card=>card.selectCard());
    await c.drawSelectedCards();
   const player=f.table.playerDoms.find(p=>p.dataset.key==='p1');
   const drawn=[...player.handArea.cardArea.children].filter(card=>card.cardRef.key.startsWith('new'));
   drawn.forEach(card=>card.selectCard());
   await c.discardSelectedCards();
    return {drawn:drawn.length,remainingHand:Object.keys(f.read('game/6/p1/hand/cards')).length};
  });
  assert.deepEqual(batch,{drawn:2,remainingHand:5});
 const local=page.locator('sg-player[data-key="p1"]');
 const playerBounds=await local.boundingBox(),toolbarBounds=await local.locator('.player-toolbar').boundingBox();
 assert.ok(toolbarBounds.x>playerBounds.x && toolbarBounds.x+toolbarBounds.width<playerBounds.x+playerBounds.width);
 const handBounds=await local.locator('sg-area.hand-area').boundingBox();
 assert.ok(handBounds.x+handBounds.width<=toolbarBounds.x);
 await local.locator('[data-action="hp-minus"]').click();
 await page.waitForFunction(()=>window.fixture.read('game/6/p1/hp')==='11/15');
 await local.locator('[data-action="hp-plus"]').click();
 await page.waitForFunction(()=>window.fixture.read('game/6/p1/hp')==='12/15');
 await local.locator('[data-action="hp-limit"]').click();
 await local.locator('.max-hp-picker').waitFor({state:'visible'});
 await local.locator('.picker-close').click();
 const sourceCard=pile.locator('sg-card').first();
 const sourceBox=await sourceCard.boundingBox();
 const localArea=local.locator('sg-area.other1-area');
 const destBox=await localArea.boundingBox();
 const priorCount=await localArea.locator('sg-card').count();
 await page.mouse.move(sourceBox.x+15,sourceBox.y+20);await page.mouse.down();
 await page.mouse.move(destBox.x+destBox.width/2,destBox.y+destBox.height/2,{steps:12});
 await page.waitForTimeout(80);await page.mouse.up();
 await page.waitForFunction(n=>Object.keys(window.fixture.read('game/6/p1/other1/cards')||{}).length===n,priorCount+1);
 assert.equal(await local.locator('.drop-picker').isVisible(),false);
 // All local card regions share overflow controls without duplicating live cards.
 await page.waitForTimeout(400); // Let the preceding drag's click-suppression window expire.
 for (const type of ['hand', 'other1', 'other2']) {
   const area=local.locator(`sg-area.${type}-area`);
   await page.evaluate(async type=>{
     const c=window.fixture.controller;
     await c.writePatch({[`game/6/p1/${type}/cards`]:{single:{id:'p1',show:'0',order:0}}});
   },type);
   await area.locator('sg-card').waitFor();
   await page.waitForFunction(type=>{
     const p=window.fixture.table.playerDoms.find(p=>p.dataset.key==='p1');
     return p[type==='hand'?'handArea':type+'Area'].scrollButtons.every(b=>b.hidden);
   },type);
   await page.evaluate(async type=>{
     await window.fixture.controller.writePatch({[`game/6/p1/${type}/cards`]:Object.fromEntries(Array.from({length:48},(_,i)=>['many'+i,{id:'p1',show:'0',order:i}]))});
   },type);
   await area.locator('.scroll-right').waitFor({state:'visible'});
   await area.locator('.card-area').evaluate(n=>{n.scrollLeft=0});
   await area.locator('.scroll-left').waitFor({state:'hidden'});
   assert.match(await area.locator('.expand-area').textContent(), /展开/);
   assert.doesNotMatch(await area.locator('.expand-area').textContent(), /48/);
   await area.locator('.scroll-right').click();
   await page.waitForFunction(type=>{
     const p=window.fixture.table.playerDoms.find(p=>p.dataset.key==='p1');
     return p[type==='hand'?'handArea':type+'Area'].cardArea.scrollLeft>0;
   },type);
   await area.locator('.scroll-left').waitFor({state:'visible'});
   await area.locator('.card-area').evaluate(n=>{n.scrollLeft=n.scrollWidth});
   await area.locator('.scroll-right').waitFor({state:'hidden'});
   await area.locator('.expand-area').click();
   await area.locator('.wrapper:popover-open').waitFor();
   assert.equal(await area.locator('sg-card').count(),48);
   assert.equal(await area.locator('.scroll-right').isVisible(),false);
   const firstCard=area.locator('sg-card').first();
   await firstCard.locator('.card-block').click();
   assert.equal(await firstCard.locator('.card-block').evaluate(n=>n.classList.contains('selected')),true);
   const rows=await area.locator('sg-card').evaluateAll(cards=>new Set(cards.map(c=>Math.round(c.getBoundingClientRect().top))).size);
   assert.ok(rows>1);
    await page.keyboard.press('Escape');
    await area.locator('.wrapper:popover-open').waitFor({state:'hidden'});
    assert.equal(await firstCard.locator('.card-block').evaluate(n=>n.classList.contains('selected')),true);
    await page.waitForFunction(type=>{
      const p=window.fixture.table.playerDoms.find(p=>p.dataset.key==='p1');
      return p[type==='hand'?'handArea':type+'Area'].cardArea.scrollLeft>0;
    },type);
   await page.evaluate(async type=>window.fixture.controller.writePatch({[`game/6/p1/${type}/cards`]:null}),type);
   await area.locator('.scroll-right').waitFor({state:'hidden'});
 }
 assert.deepEqual(errors,[]);
 console.log('PASS: 100-card layout, hidden pile faces, sorting, player highlight, cancel, confirmed move.');
 await browser.close();
})().catch(error=>{console.error(error);process.exit(1)});
